### ISSUE TITLE
I can't find "Data\HRTF_Typical_Bat" in "Data",when I run "r2_convertDataSetNERF_STFT.m"

### ISSUE THREAD

**Issue by lonelypatients1231** [Cosys-Lab/SonoNERF#1]
Hay , when I read your Paper ，I was very interested in your paper and wanted to learn about it, and I was very excited when I found out that you made the source code public, and I couldn't help but run it, but unfortunately, 
I can't find "Data\HRTF_Typical_Bat" in "Data",when I run "r2_convertDataSetNERF_STFT.m", and r3,r4,r5 have the same problems, 
If it is convenient for you, could you please provide complete documents and simple examples for complete learning，
I am looking forward to your replay

**Comment by WouterJansen** [comment]
Hi, you are correct! Due to the .gitignore file the _.mat_ files were being ignored and I did not notice this when pushing my commits. I apologize! I have now fixed this and they are included in this repository now. Let me know if you have any more questions or issues :) 

Note that the large data files (.mat files in _/Data_ and _/DataCalculated/Simulations_) are stored using LFS on this repository. Cloning this repository will include these files but downloading the repository as a ZIP will not.
